### PR TITLE
Adding ESLint-Plugin-Excel-Custom-Functions to Shared App Template

### PR DESCRIPTION
**Pull request by arttarawork**

### CODE REVIEW

**Comment by TCourtneyOwen** [comment]
So how does this work? Does the user need to launch linting somehow? Is it all done via the existing lint script (npm run lint)?

**Comment by arttarawork** [comment]
> So how does this work? Does the user need to launch linting somehow? Is it all done via the existing lint script (npm run lint)?

So, users can either run "npm run lint", or they can use the following extension in VS Code to have the problematic code highlighted: https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

**Comment by TCourtneyOwen** [comment]
Did you validate that the linter passes locally with your changes?  If so, I will merge your branch to the shared to shared-app branch

**Comment by TCourtneyOwen** [comment]
I received the following linting errors with your changes:

C:\Excel-Custom-Functions\src\functions\functions.ts
  21:18  warning  No Office API read calls within Custom Functions   excel-custom-functions/no-office-read-calls
  21:18  error    No Office API write calls within Custom Functions  excel-custom-functions/no-office-write-calls

✖ 2 problems (1 error, 1 warning)

So we should probably remove the Clock function which makes read calls

**Comment by arttarawork** [comment]
The only specific issue I've noticed is that in the standard functions.ts file, the linter assumes currentTime() is an office.js call, or uses office.js calls.

image

This isn't replicable with other functions in a straightforward way, so I think this is some weird edge case we missed with ESLint-Plugin-Excel-Custom-Functions. 

The actual implementation of the linter within the project works well, though. "npm run test" comes back clean.

**Comment by TCourtneyOwen** [comment]
We can simply remove the clock and currentTime functions if indeed they are examples of the type of read operations we don't want users doing

**Comment by arttarawork** [comment]
Those functions should be totally fine, since they don't call any Office.js functions. I think this is an issue with the shared-app linter itself, that needs to be resolved. We can remove those two functions, but there's nothing inherently wrong with them.

**Pull request merged**
